In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
vec = np.arange(1, 4)
vec

array([1, 2, 3])

In [3]:
mat = np.arange(6).reshape(3, -1)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
vec @ mat

array([16, 22])

In [5]:
vecmat = np.arange(1, 7).reshape(-1, 3)
vecmat

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
vecmat @ mat

array([[16, 22],
       [34, 49]])

In [7]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
np.sum(mat, axis=1, keepdims=True)

array([[1],
       [5],
       [9]])

In [9]:
np.log(mat)

array([[      -inf, 0.        ],
       [0.69314718, 1.09861229],
       [1.38629436, 1.60943791]])

In [10]:
q = np.array([2, 3, 5])
np.argmax(q)

2

In [11]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
np.argmax(mat, axis=1)

array([1, 1, 1], dtype=int64)

In [13]:
np.log(q)

array([0.69314718, 1.09861229, 1.60943791])

In [14]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
q = np.array([1, 2, 3])
w = np.array([4])
np.concatenate([q, w], axis=0)
q[-1:]

array([3])

In [16]:
np.array([q]).T

array([[1],
       [2],
       [3]])

In [17]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
mat[2:3, :].T

array([[4],
       [5]])

In [19]:
b1 = np.random.rand(1, 5)
b1

array([[0.78376085, 0.06105676, 0.35953587, 0.31282776, 0.981557  ]])

In [20]:
vec2 = np.array([vec])
vec2

array([[1, 2, 3]])

In [21]:
b1.T @ vec2

array([[0.78376085, 1.56752169, 2.35128254],
       [0.06105676, 0.12211352, 0.18317028],
       [0.35953587, 0.71907175, 1.07860762],
       [0.31282776, 0.62565553, 0.93848329],
       [0.981557  , 1.963114  , 2.94467099]])

In [53]:
vec1 = np.array([1, 2], ndmin=2)
# vec1 = np.array([[1, 2], [1, 2]], ndmin=2)
vec1

array([[1, 2]])

In [60]:
vec2 = np.array([10, 20, 30], ndmin=2)
vec2

array([[10, 20, 30]])

In [63]:
vec1.T @ vec2

array([[10, 20, 30],
       [20, 40, 60]])