In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
vec = np.arange(1, 4)
vec

array([1, 2, 3])

In [10]:
mat = np.arange(6).reshape(3, -1)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
vec @ mat

array([16, 22])

In [13]:
vecmat = np.arange(1, 7).reshape(-1, 3)
vecmat

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
vecmat @ mat

array([[16, 22],
       [34, 49]])

In [16]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
np.sum(mat, axis=1, keepdims=True)

array([[1],
       [5],
       [9]])

In [21]:
np.log(mat)

array([[      -inf, 0.        ],
       [0.69314718, 1.09861229],
       [1.38629436, 1.60943791]])

In [23]:
q = np.array([2, 3, 5])
np.argmax(q)

2

In [24]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
np.argmax(mat, axis=1)

array([1, 1, 1], dtype=int64)

In [30]:
np.log(q)

array([0.69314718, 1.09861229, 1.60943791])

In [31]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
q = np.array([1, 2, 3])
w = np.array([4])
np.concatenate([q, w], axis=0)
q[-1:]

array([3])

In [48]:
np.array([q]).T

array([[1],
       [2],
       [3]])

In [57]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [59]:
mat[2:3, :].T

array([[4],
       [5]])

In [61]:
b1 = np.random.rand(1, 5)
b1

array([[0.64619664, 0.01995177, 0.01891447, 0.08992646, 0.65656754]])

In [64]:
vec2 = np.array([vec])
vec2

array([[1, 2, 3]])

In [65]:
b1.T @ vec2

array([[0.64619664, 1.29239328, 1.93858993],
       [0.01995177, 0.03990353, 0.0598553 ],
       [0.01891447, 0.03782895, 0.05674342],
       [0.08992646, 0.17985293, 0.26977939],
       [0.65656754, 1.31313508, 1.96970263]])