In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def set_cleardw(dw):
    for i in range(len(dw)):
        dw[i][:] = 0

In [3]:
q = [0] * 3
q[0] = np.array([13, 52, 73])
q[1] = np.arange(5)
q[2] = np.array([4])
q

[array([13, 52, 73]), array([0, 1, 2, 3, 4]), array([4])]

In [4]:
clear_dw(q)
q

NameError: name 'clear_dw' is not defined

In [125]:
q = np.array([1, 2, 3])
np.log(q)

array([0.        , 0.69314718, 1.09861229])

In [129]:
def plus(a, b):
    return a + b


q = 3
w = 2
func = plus
func(q, w)

5

In [14]:
def relu_derivative(target):
    derivative = np.ones_like(target)
    derivative[target < 0] = 0
    return derivative

q = np.array([1, -2, 0])
w = relu_derivative(q)
# q[0] = 10
print(q)
print(w)

[ 1 -2  0]
[1 0 1]


In [17]:
q = np.arange(9).reshape(3, 3)
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
np.min(q, axis=0)

array([0, 1, 2])

In [22]:
q[:, 0]

array([0, 3, 6])