In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
vec = np.arange(1, 4)
vec

array([1, 2, 3])

In [3]:
mat = np.arange(6).reshape(3, -1)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
vec @ mat

array([16, 22])

In [5]:
vecmat = np.arange(1, 7).reshape(-1, 3)
vecmat

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
vecmat @ mat

array([[16, 22],
       [34, 49]])

In [7]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
np.sum(mat, axis=1, keepdims=True)

array([[1],
       [5],
       [9]])

In [9]:
np.log(mat)

array([[      -inf, 0.        ],
       [0.69314718, 1.09861229],
       [1.38629436, 1.60943791]])

In [10]:
q = np.array([2, 3, 5])
np.argmax(q)

2

In [11]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
np.argmax(mat, axis=1)

array([1, 1, 1], dtype=int64)

In [13]:
np.log(q)

array([0.69314718, 1.09861229, 1.60943791])

In [14]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
q = np.array([1, 2, 3])
w = np.array([4])
np.concatenate([q, w], axis=0)
q[-1:]

array([3])

In [16]:
np.array([q]).T

array([[1],
       [2],
       [3]])

In [17]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
mat[2:3, :].T

array([[4],
       [5]])

In [19]:
b1 = np.random.rand(1, 5)
b1

array([[0.98560003, 0.37601027, 0.18512502, 0.5861521 , 0.8116284 ]])

In [20]:
vec2 = np.array([vec])
vec2

array([[1, 2, 3]])

In [21]:
b1.T @ vec2

array([[0.98560003, 1.97120005, 2.95680008],
       [0.37601027, 0.75202055, 1.12803082],
       [0.18512502, 0.37025004, 0.55537506],
       [0.5861521 , 1.17230419, 1.75845629],
       [0.8116284 , 1.62325681, 2.43488521]])

In [22]:
vec1 = np.array([1, 2], ndmin=2)
# vec1 = np.array([[1, 2], [1, 2]], ndmin=2)
vec1

array([[1, 2]])

In [23]:
vec2 = np.array([10, 20, 30], ndmin=2)
vec2

array([[10, 20, 30]])

In [24]:
vec1.T @ vec2

array([[10, 20, 30],
       [20, 40, 60]])

In [25]:
mat1 = np.arange(9).reshape(3, 3)
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
mat2 = np.arange(10, 70, 10).reshape(3, 2)
mat2

array([[10, 20],
       [30, 40],
       [50, 60]])

In [27]:
mat3 = np.concatenate((mat1, mat2), axis=1)
np.random.shuffle(mat3)
mat3

array([[ 3,  4,  5, 30, 40],
       [ 0,  1,  2, 10, 20],
       [ 6,  7,  8, 50, 60]])

In [28]:
mat1 = mat3[:, :-2]
mat1

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [29]:
mat2 = mat3[:, -2:]
mat2

array([[30, 40],
       [10, 20],
       [50, 60]])

In [30]:
0.1 * 0.1

0.010000000000000002

In [31]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
0.1 * mat

array([[0. , 0.1],
       [0.2, 0.3],
       [0.4, 0.5]])

In [34]:
np.full((2, 2), 2)

array([[2, 2],
       [2, 2]])

In [35]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
mat ** 2

array([[ 0,  1],
       [ 4,  9],
       [16, 25]], dtype=int32)

In [37]:
np.power(mat, 2)

array([[ 0,  1],
       [ 4,  9],
       [16, 25]], dtype=int32)