In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
vec = np.arange(1, 4)
vec

array([1, 2, 3])

In [10]:
mat = np.arange(6).reshape(3, -1)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
vec @ mat

array([16, 22])

In [13]:
vecmat = np.arange(1, 7).reshape(-1, 3)
vecmat

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
vecmat @ mat

array([[16, 22],
       [34, 49]])

In [16]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
np.sum(mat, axis=1, keepdims=True)

array([[1],
       [5],
       [9]])

In [21]:
np.log(mat)

array([[      -inf, 0.        ],
       [0.69314718, 1.09861229],
       [1.38629436, 1.60943791]])