In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [42]:
q = np.array([1, 2, 3])
q

array([1, 2, 3])

In [43]:
w = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
w = np.random.rand(3, 4)
w

array([[0.49432199, 0.65157575, 0.0406635 , 0.23047891],
       [0.01548562, 0.94404947, 0.14852308, 0.0174188 ],
       [0.76321991, 0.55919119, 0.38718485, 0.88660496]])

In [48]:
q @ w

array([2.81495297, 4.21724827, 1.4992642 , 2.92513137])

In [49]:
q

array([1, 2, 3])

In [62]:
np.concatenate((q, [1]))

array([1, 2, 3, 1])

In [63]:
q

array([1, 2, 3])

In [64]:
1 - q

array([ 0, -1, -2])

In [65]:
np.log(q)

array([0.        , 0.69314718, 1.09861229])

In [69]:
q = np.array([1, 2])
w = np.array([30, 40])
w - q

array([29, 38])

In [76]:
q = np.array([1, 2])
e = np.array([20, 30, 40])
q * e.reshape(-1, 1)

array([[20, 40],
       [30, 60],
       [40, 80]])

In [79]:
q.reshape(-1, 1) * e

array([[20, 30, 40],
       [40, 60, 80]])

In [86]:
a = q * np.array([e]).T
a

array([[20, 40],
       [30, 60],
       [40, 80]])

In [89]:
s = np.arange(1, 7).reshape(3, 2)
s

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
a - s

array([[19, 38],
       [27, 56],
       [35, 74]])

In [92]:
q = np.array([1, 2])
w = np.array([10, 20])
q @ w

50

In [113]:
q = np.array([1, 2, 3, 4])
for i in range(1, 5, -1):
    print(i)